name: MegaMarket CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-denetimi:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu GitHub'dan Cek
      uses: actions/checkout@v3

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Bagimliliklari Yukle
      run: |
        pip install flask pytest

    - name: Testleri Kostur
      run: |
        python -m pytest
        