name: MegaMarket CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-denetimi:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu GitHub'dan Çek
      uses: actions/checkout@v3

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Bağımlılıkları Yükle
      run: |
        pip install flask pytest

    - name: Testleri Koştur
      run: |
        python -m pytest
        